select* from customer limit 10

--1. What is the total revenue generated by male vs. female customer?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
--2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount)from customer)
--3. Which are the top 5 products with the highest average review rating?
--4. Compare the average Purchase Amounts between Standard and Express Shipping.
--5. Do subscribed customers spend more? Compare average spend and total revenue between subsribers and non-subscribers.
--6. Which 5 products have the highest percentage of purchase with discounts applied?